replicaCount: 1

image:
  repository: cele/acrn
  tag: latest

service:
  targetPort: 3000

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

resources:
  requests:
    memory: "128Mi"
    cpu: "125m"
  limits:
    memory: "256Mi"
    cpu: "250m"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "example.com"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - "example.com"
      secretName: example-tls

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
