# Example GitHub Actions workflow for deploying to AWS App Runner
# Using OIDC (OpenID Connect) - No AWS credentials stored in GitHub!

name: Deploy Infrastructure to AWS App Runner

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

# Required for OIDC authentication
permissions:
  id-token: write   # Allows the workflow to request an OIDC token
  contents: read    # Allows reading the repository contents

env:
  AWS_REGION: us-east-1
  TERRAFORM_DIR: terraform

jobs:
  terraform:
    name: Terraform Plan/Apply
    runs-on: ubuntu-latest
    
    # Use GitHub Environments to securely manage prod/dev secrets
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get OIDC Token Subject
        uses: actions/github-script@v6
        id: get_token_subject
        with:
          script: |
            const core = require('@actions/core');
            const idToken = await core.getIDToken();
            const payload = JSON.parse(Buffer.from(idToken.split('.')[1], 'base64').toString());
            core.setOutput('subject', payload.sub);
      - name: Display OIDC Token Subject
        run: echo "OIDC Subject: ${{ steps.get_token_subject.outputs.subject }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Uses the secret from the GitHub Environment
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-Terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          WORKSPACE="dev" # Default to dev
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            WORKSPACE="prod"
          fi

          terraform init \
            -backend-config="bucket=tf-state-acrn-dev" \
            -backend-config="key=${WORKSPACE}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=tf-lock-acrn"

      - name: Select Terraform Workspace
        id: workspace
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            terraform workspace select prod
          else
            terraform workspace select dev
          fi
      
      - name: Terraform Format Check
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          VAR_FILE="dev.tfvars"
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            VAR_FILE="prod.tfvars"
          fi
          terraform plan -no-color -var-file="$VAR_FILE"

      - name: Terraform Apply
        if: github.ref_name == 'master' && github.event_name == 'push'
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          # The var file is always prod.tfvars in the apply step
          terraform apply -auto-approve -var-file="prod.tfvars"

# ============================================================================
# Setup Instructions:
# ============================================================================
# 
# 1. Enable GitHub Actions OIDC in your Terraform:
#    
#    In terraform.tfvars, add:
#    enable_github_actions_oidc = true
#    github_repo                = "your-username/acrn-react"
#
# 2. Run terraform apply to create the OIDC provider and role
#
# 3. Get the role ARN:
#    terraform output github_actions_role_arn
#
# 4. Add the ARN as a GitHub secret:
#    - Go to: Settings > Secrets and variables > Actions
#    - Click "New repository secret"
#    - Name: AWS_ROLE_ARN
#    - Value: (paste the ARN from step 3)
#
# 5. Copy this file to: .github/workflows/deploy.yml
#
# 6. Commit and push - the workflow will run automatically!
#
# ============================================================================
# Security Benefits:
# ============================================================================
#
# ✅ No AWS credentials stored in GitHub
# ✅ Temporary credentials (auto-expire)
# ✅ Fine-grained permissions via IAM role
# ✅ Auditable via CloudTrail
# ✅ Can't be leaked or stolen
# ✅ Automatically rotated every workflow run
#
# ============================================================================

