name: Docker Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'apprunner.yaml'
      - 'TODO.md'
  pull_request:
    branches:
      - master    
    paths-ignore:
      - 'README.md'
      - 'apprunner.yaml'
      - 'TODO.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cele/acrn-react
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}